In [13]:
import numpy as np

In [14]:
#create array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [15]:
#Create Matrix
b = np.array([[1,2],[3, 4]])
b

array([[1, 2],
       [3, 4]])

In [16]:
#shape
print(a.shape,b.shape)

(4,) (2, 2)


In [17]:
#reshape
c=a.reshape((4,1))
c.shape

(4, 1)

In [18]:
d = a.reshape((2,-1,1))
d.shape

(2, 2, 1)

In [19]:
#concatenate
a=np.array([1,2,3])
b=np.array([4,5])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5])

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c=a+b
c

array([5, 7, 9])

In [21]:
e=a+5
e

array([6, 7, 8])

In [22]:
a = np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [27]:
b = a[2:7]
b

array([3, 4, 5, 6, 7])

In [29]:
c = a[2:7:2]
c

array([3, 5, 7])

In [30]:
c = a[a>3]
c

array([4, 5, 6, 7, 8])

In [31]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
sum_a = np.sum(a)
sum_a

36

In [34]:
max_a = np.max(a)
max_a

1

In [35]:
min_a = np.min(a)
min_a

1

In [36]:
a = np.array([3,6,1,9,5,4,1,4])
b = np.sort(a)
b

array([1, 1, 3, 4, 4, 5, 6, 9])

In [38]:
a= np.random.randint(-100,100,(3,4))
a

array([[-50,  -8,  96, -92],
       [-97, -96, -43,  63],
       [ 74,  -2,  96,  42]])

In [39]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c = np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [46]:
#normalize
a = np.array([1,2,3])
a

array([1, 2, 3])

In [43]:
ma = np.mean(a)
ma

2.0

In [47]:
std_a = np.std(a)
std_a

0.816496580927726

In [48]:
norm_a = (a-ma)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [49]:
m= np.mean(norm_a)
m

0.0

In [50]:
s = np.std(norm_a)
s

0.9999999999999999