In [10]:
import numpy as np

In [11]:
#create array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [12]:
#Create Matrix
b = np.array([[1,2],[3, 4]])
b

array([[1, 2],
       [3, 4]])

In [13]:
#shape
print(a.shape,b.shape)

(4,) (2, 2)


In [14]:
#reshape
c=a.reshape((4,1))
c.shape

(4, 1)

In [15]:
d = a.reshape((2,-1,1))
d.shape

(2, 2, 1)

In [16]:
#concatenate
a=np.array([1,2,3])
b=np.array([4,5])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5])

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c=a+b
c

array([5, 7, 9])

array([11, 12, 13])